version: "3.8"

services:
  createleaguedb:
    image: ayaansethii/createleaguedb
    container_name: createleaguedb
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: student
    volumes:
      - ./createleaguedb/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - nba-net

  searchleaguedb:
    image: ayaansethii/searchleaguedb
    container_name: searchleaguedb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: student
    volumes:
      - ./searchleaguedb/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - nba-net

  accountsdb:
    image: ayaansethii/accountsdb
    container_name: accountsdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: student
    volumes:
      - ./accountsdb/initdb.d:/docker-entrypoint-initdb.d
    networks:
      - nba-net

  createleague:
    image: ayaansethii/createleague
    container_name: createleague
    ports:
      - "8081:8080"
    depends_on:
      - createleaguedb
    networks:
      - nba-net

  searchleague:
    image: ayaansethii/searchleague
    container_name: searchleague
    ports:
      - "8082:8080"
    depends_on:
      - searchleaguedb
    networks:
      - nba-net

  frontend:
    image: ayaansethii/frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - accountsdb
      - createleague
      - searchleague
    networks:
      - nba-net

  kubemq:
    image: kubemq/kubemq-community:latest
    container_name: kubemq
    ports:
      - "8090:8080"  # Web UI
      - "50000:50000"  # gRPC default port
    networks:
      - nba-net

networks:
  nba-net:
    driver: bridge
