CREATE DATABASE IF NOT EXISTS LEAGUES_DBS;
USE LEAGUES_DBS;

DROP TABLE League;

CREATE TABLE League (
    leagueID INT AUTO_INCREMENT PRIMARY KEY,
    leagueName VARCHAR(50) NOT NULL,
    managerID INT NOT NULL  
);

INSERT INTO League (leagueName, managerID) VALUES ("NBA", 1);
