CREATE DATABASE IF NOT EXISTS NBASW;
USE NBASW;


CREATE TABLE IF NOT EXISTS Manager (
    managerID INT PRIMARY KEY,
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(30) NOT NULL
);


CREATE TABLE IF NOT EXISTS League (
    leagueID INT PRIMARY KEY,
    leagueName VARCHAR(50) NOT NULL,
    managerID INT,  
    FOREIGN KEY (managerID) REFERENCES Manager(managerID) ON DELETE SET NULL
);
